### ISSUE TITLE
There is a Fatal exception when attempting to  switch from Inline Scenario to Scenario or Use-Condition

### ISSUE THREAD

**Issue by organik1** [renyuneyun/Easer#108]
Hello Dev!
It is really nice to see that you respond swiftly to issues and then work on a fix ASAP.

I noticed this bug while trying to set up Easer on my Android 4.2.2 jelly device.
It happens that when attempting to  switch from ``inline-scenario`` to either ``Scenario`` or ``use condition``, the app crashes.
This did come as a surprise because I didn't face the issue while using Easer on my 6.0 marshmallow device. 
That is why I have added my log below. I hope it helps

```05-21 06:31:44.228 E/        (2581): appName=ryey.easer, acAppName=com.android.browser
05-21 06:31:44.228 E/        (2581): 0
05-21 06:31:47.291 E/dalvikvm(2581): Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.z$a.<init>
05-21 06:31:54.490 E/AndroidRuntime(2581): FATAL EXCEPTION: main
05-21 06:31:54.490 E/AndroidRuntime(2581): java.lang.IllegalStateException: Must measure with an exact width
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.support.v4.view.PagerTitleStrip.onMeasure(Unknown Source)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.support.v4.view.u.onMeasure(Unknown Source)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.support.constraint.ConstraintLayout.onMeasure(Unknown Source)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(Unknown Source)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1452)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:600)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2203)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.View.measure(View.java:15783)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2212)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1291)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1486)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1181)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4942)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.Choreographer.doFrame(Choreographer.java:548)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.os.Handler.handleCallback(Handler.java:800)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.os.Looper.loop(Looper.java:194)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at android.app.ActivityThread.main(ActivityThread.java:5370)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at java.lang.reflect.Method.invoke(Method.java:525)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
05-21 06:31:54.490 E/AndroidRuntime(2581): 	at dalvik.system.NativeStart.main(Native Method)
05-21 06:31:54.539 E/AppErrorDialog(881): Failed to get ILowStorageHandle instance
05-21 06:31:57.061 E/InputDispatcher(881): channel '41bea580 ryey.easer/ryey.easer.core.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-21 06:31:57.062 E/InputDispatcher(881): channel '417d7570 ryey.easer/ryey.easer.core.ui.edit.EditScriptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!```

**Comment by organik1** [comment]
Update!!

If you will find a record of this issue helpful, please I'll be glad to provide one.

**Comment by renyuneyun** [comment]
Hmm, that's strange. My attemp to reproduce doesn't crash (but I'm on 6.0).

The log seems to indicate there is some problem in the UI design (because ti crashes on some Android UI component, rather than in Easer's logic).
Could you provide detailed steps for this to happen?

E.g.
1. Open the edit page of an existing Script (which uses inline Scenario)
2. Switch from "inline Scenario" to "Scenrio" (or "Condition")
3. App crashes
(though in my try, the 3rd point doesn't happen.)

**Comment by organik1** [comment]
I own a 6.0 device and the experience there is different.. This particular issue is rather exclusive to Android 4.2.2 jelly bean...
I'll include that video now below this post..

**Comment by organik1** [comment]
https://vimeo.com/271070720

There you go
