### ISSUE TITLE
[EaserOperationPluginExample] Crashing After Ending Activity

### ISSUE THREAD

**Issue by coxtor** [renyuneyun/Easer#194]
I have posted this issue in the corresponding repo to, but am unsure how frequent it is checked.

When executing the example plugin this error occurs:

`2018-11-20 15:25:30.182 22960-22960/? E/AndroidRuntime: FATAL EXCEPTION: main Process: ryey.easeroperationpluginexample, PID: 22960 java.lang.IllegalStateException: Could not find method finishActivity(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'btn_accept' at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:423) at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:380) at android.view.View.performClick(View.java:6294) at android.view.View$PerformClick.run(View.java:24770) at android.os.Handler.handleCallback(Handler.java:790) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6494) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by renyuneyun** [comment]
Hi there,
The error seems strange at my first glance. I'll try to figure it out soon.

In the meantime: do you use any methods to limit the background behaviour of apps? Especially in "Developer Settings"?

**Comment by coxtor** [comment]
Hmm, good question, I am using LineageOS 15.1 with MicroG .  I have disabled all things such as battery optimization etc. 
Easer works as expected using integrated profiles etc, such as listening for broadcasts. Can I provide any more useful information in order to fix this? 
I am currently working on a mqtt extension for easer as a third party Plugin.
