### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by nicobo** [renyuneyun/Easer#198]
Hi.

I'm trying to reuse the *Tasker* *BroadcastReceiver* of [this app](https://git.frostnerd.com/PublicAndroidApps/DnsChanger), into Easer.

The [*Intent* looks very simple](https://git.frostnerd.com/PublicAndroidApps/DnsChanger/blob/master/app/src/main/java/com/frostnerd/dnschanger/tasker/FireReceiver.java) :
- action : `com.twofortyfouram.locale.intent.action.FIRE_SETTING`
- extra : key = `com.frostnerd.dnschanger.resumedns` ; value = any value (not used)

However when I trigger such a profile within Easer, I've this error in *logcat* :

```
12-10 00:37:41.699  4575  4575 E PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │ Thread: main
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │ ProfileLoaderService.a  (null:-1)
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │    ProfileLoaderService.a  (null:-1)
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │ error while loading operation <g> for profile <Resume DNS> : java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.plugins.operation.d.a.a(Unknown Source)
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.plugins.operation.d.a.a(Unknown Source)
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.ProfileLoaderService.a(Unknown Source)
12-10 00:37:41.701  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.ProfileLoaderService.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.ProfileLoaderService$a.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.a$a.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.a$a.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.a$a.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.d.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.d.a(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at ryey.easer.core.d$1.onReceive(Unknown Source)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at android.os.Handler.handleCallback(Handler.java:751)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at android.os.Looper.loop(Looper.java:154)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at android.app.ActivityThread.main(ActivityThread.java:6128)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at java.lang.reflect.Method.invoke(Native Method)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: │       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-10 00:37:41.702  4575  4575 E PRETTY_LOGGER: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I cannot identify the faulty class/line so I've tried to put a value in all fields (action, category, type, data, extra : key + value ; tried both *int* and *String*) to no avail...

I'm using Easer 0.7.2-alpha

**Comment by nicobo** [comment]
I'm on Android 7.1.2

**Comment by renyuneyun** [comment]
Thanks for reporting! It seems I there is still corner cases I failed to handle. I'll fix this soon, hopefully in the next release (or the next minor fix to it).
