### ISSUE TITLE
Fdroid build of 0.7.7.6 does not run

### ISSUE THREAD

**Issue by mase76** [renyuneyun/Easer#237]
Hi!
Since the update to 0.7.7.6 from Fdroid, the app does not run any more. I only get a white screen, and the Android asks to close it. I did a fresh install of the app and get this issue on 2 Pie devices.

**Comment by GuepardoApps** [comment]
Hi. I got the same issue. It seams like it is located in the LocalSkillRegistry line 113. ConnectivityUSourceSkill gets registered here. As soon as I remove it and rebuild the application it is working again.

The Error thrown with ConnectivityUSourceSkill  registered is a java.lang.StackOverflowError: stack size 8MB

`at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
2019-07-30 21:26:46.441 11388-11388/ryey.easer E/ACRA:     at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.usource.connectivity.ConnectivityUSourceSkill.event(ConnectivityUSourceSkill.java:106)
        at ryey.easer.skills.LocalSkillRegistry.<init>(LocalSkillRegistry.java:122)
        at ryey.easer.skills.LocalSkillRegistry.<clinit>(LocalSkillRegistry.java:162)
        at ryey.easer.skills.LocalSkillRegistry.getInstance(Unknown Source:0)
        at ryey.easer.core.ui.PermissionOutlineFragment.hasAllRequiredPermissions(PermissionOutlineFragment.java:82)
        at ryey.easer.core.ui.PermissionOutlineFragment.onResume(PermissionOutlineFragment.java:72)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2498)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2504)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:223)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7583)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4000)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4040)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

**Comment by GuepardoApps** [comment]
It seems the cause is in the implementation of the ConnectivityUSourceSkill itself.
The implementation overrides the deprecated event() method [here](https://github.com/renyuneyun/Easer/blob/6d36509288dca6d3110bce3217640ee656bbc9a9/app/src/main/java/ryey/easer/skills/usource/connectivity/ConnectivityUSourceSkill.java#L106) and calls itself infinite! These leads to the overflow.

**Comment by gruentee** [comment]
I can confirm the issue.

**Comment by racuna** [comment]
Same here with MIUI 10 (Android 9). Beta 0.7.7.8 can run, but some scripts dissapear after I convert them to new format, so I went back to 0.7.6.2

**Comment by renyuneyun** [comment]
Sorry to the stupid bug...
I merged #239 . Thanks @GuepardoApps !

I'll do some final checks and then make it a release today.

**Comment by renyuneyun** [comment]
@racuna Do you still remember what scripts disappeared? That will help to pin down the cause.
