### ISSUE TITLE
Error/crash when selecting "extras" in Send Broadcast operation

### ISSUE THREAD

**Issue by madalu** [renyuneyun/Easer#242]
When attempting to create a Send Broadcast operation within a profile, Easer crashes when I press on the "extras" button.

This occurs with version 0.7.7.7 on Android 8.1.0.

Here is the stacktrace generated with logging:

```
BUILD_CONFIG: {}
APP_VERSION_CODE: 116
USER_CRASH_DATE: 2019-08-11T13:11:46.481-05:00
ANDROID_VERSION: 8.1.0
BRAND: motorola
PHONE_MODEL: Moto G (5S) Plus
PRODUCT: sanders
STACK_TRACE: java.lang.IllegalStateException: Fragment ryey.easer.skills.operation.EditExtraFragment.a must be a public static class to be  properly recreated from instance state.
	at b.j.a.a.a(BackStackRecord.java:71)
	at b.j.a.a.a(BackStackRecord.java:56)
	at ryey.easer.skills.operation.c.onClick(EditExtraFragment.java:3)
	at android.view.View.performClick(View.java:6297)
	at android.view.View$PerformClick.run(View.java:24797)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6626)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by renyuneyun** [comment]
Thanks for reporting!
This seems to be a UI bug and should be resolved soon. (The cause is quite direct based on the log.)

**Comment by laarmen** [comment]
I think this might also cause an error when trying to log a more standard broadcast. I have the following stack trace (output ten times in the ADB logs), even though I haven't added any "extras" in my profile.

```
08-17 12:30:32.009 19607 19607 W System.err: org.json.JSONException: End of input at character 0 of 
08-17 12:30:32.009 19607 19607 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
08-17 12:30:32.009 19607 19607 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
08-17 12:30:32.009 19607 19607 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:92)
08-17 12:30:32.010 19607 19607 W System.err: 	at org.json.JSONArray.<init>(JSONArray.java:108)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.skills.operation.h.<init>(Extras.java:6)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.skills.operation.d.d.a(BroadcastOperationData.java:14)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.skills.operation.d.d.<init>(BroadcastOperationData.java:7)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.skills.operation.d.e.a(BroadcastOperationDataFactory.java:3)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.skills.operation.d.e.a(BroadcastOperationDataFactory.java:1)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.c.a(ProfileParser.java:16)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.c.a(ProfileParser.java:7)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.c.a(ProfileParser.java:1)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.d.a(FileDataStorageBackendHelper.java:2)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.b.a(JsonProfileDataStorageBackend.java:4)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.b.a(JsonProfileDataStorageBackend.java:11)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a.c.b.list(JsonProfileDataStorageBackend.java:2)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.a.a.a.a(AbstractDataStorage.java:2)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.ui.data.profile.h.f(ProfileListFragment.java:3)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.ui.a.a.g(AbstractDataListFragment.java:2)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.ui.a.a.e(AbstractDataListFragment.java:1)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.ui.a.a.b(AbstractDataListFragment.java:1)
08-17 12:30:32.010 19607 19607 W System.err: 	at ryey.easer.core.ui.a.j.onActivityResult(DataListContainerFragment.java:1)
08-17 12:30:32.010 19607 19607 W System.err: 	at b.j.a.k.onActivityResult(FragmentActivity.java:7)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4375)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4424)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.os.Looper.loop(Looper.java:280)
08-17 12:30:32.010 19607 19607 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6706)
08-17 12:30:32.010 19607 19607 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 12:30:32.010 19607 19607 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-17 12:30:32.010 19607 19607 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-17 12:30:32.010 19607 19607 W System.err: ryey.easer.a.a.b: End of input at character 0 of 
```

**Comment by renyuneyun** [comment]
Thanks, @laarmen . It seems there is some problem with the serialisation. I'll investigate both problems.
