### ISSUE TITLE
Event "Cell Location" not working on some devices

### ISSUE THREAD

**Issue by wei3er** [renyuneyun/Easer#251]
The Event "Cell Location" works on Oneplus 6 but not on Google Pixel (same Android version).
No cell id is shown an the loading indicator is rotating infinately.

This bug was found on Google Pixel (sailfish), Android 9, Release 0.7.7.7

**Comment by renyuneyun** [comment]
Thanks for reporting.
Is there any permission issue?

**Comment by cyko69** [comment]
Same for Xiaomi Redmi Note 5 running LineageOs 16.0
Easer is grant every permission I could find.
Also "Wifi Connection" has the same behavior.

**Comment by wei3er** [comment]
No. All permissions are granted.

This is no general issue - it work's fine on a Oneplus 6, but not on Google Pixel or Xiaomi Redmi Note 6 ...

**Comment by cyko69** [comment]
OS update fixed it for me.

**Comment by wei3er** [comment]
Release 0.7.8.1 fixed the issue for for Google Pixel (sailfish), Android 9

**Comment by NiklasTheis** [comment]
I also habe this issue on a Motorolo Moto X4.
My solution was to manually enable the location services (GPS) otherwise I was not able to assign any cell locations.
Maybe you could add a check for the location services active and if not activate them.
Regards.

**Comment by renyuneyun** [comment]
@NiklasTheis Hmm, good point, though should be rephrased.
I can call the specific system setting to let the user to turn on location service, but can't do it from Easer any more (Android restriction).

But essentially, when serving in the background, I don't think there could be any checks. The user should be aware what they are doing...

**Comment by subiol** [comment]
The Event Cell Location does not work in my Pocophone F1 running official LineageOS  17, no Gapps.

The list appears but remains unpopulated no matter how much I wait. I receive signal in both my SIM card accounts, is it possible it is a problems with the two SIM cards?

If I press OK while the list is empty, Easer quits with an error. Here is the log of the error:

BUILD_CONFIG: {}
APP_VERSION_CODE: 123
USER_CRASH_DATE: 2020-05-17T22:19:44.314+03:00
ANDROID_VERSION: 10
BRAND: Xiaomi
PHONE_MODEL: POCO F1
PRODUCT: beryllium
STACK_TRACE: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:77)
	at ryey.easer.j.h.g.c.a(CellLocationSkillViewFragment.java:7)
	at ryey.easer.j.h.a.a(ScannerDialogFragment.java:3)
	at ryey.easer.j.h.a$b.onClick(ScannerDialogFragment.java:1)
	at androidx.appcompat.app.AlertController$g.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
