### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sphh** [renyuneyun/Easer#290]
**Describe the bug**
Easer crashes when I save a new script.

**To Reproduce**
1. Install Easer 0.7.9beta from F-Droid
2. Start Easer
3. `Turn on External logging` (Grant access...)
4. Stop Easer
5. Start Easer
6. Create Event: Timer: Longer Time / Inexact / 1 Minutes / One Time
7. Create Profile: WiFi On
8. Create Script: Profile as above, Event as above / Repeatable / Volatile
9. Save → Crash

**Expected behavior**
Well, it should not crash.

**Error log:**
```
BUILD_CONFIG: {}
APP_VERSION_CODE: 121001
USER_CRASH_DATE: 2019-11-13T10:20:21.344+01:00
ANDROID_VERSION: 8.1.0
BRAND: Unihertz
PHONE_MODEL: Jelly-Pro
PRODUCT: Jelly-Pro
STACK_TRACE: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Set.size()' on a null object reference
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:7)
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:1)
	at ryey.easer.core.a.a.a.d.a(FileDataStorageBackendHelper.java:8)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:7)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:1)
	at ryey.easer.core.a.a.a.a(AbstractDataStorage.java:10)
	at ryey.easer.core.ui.a.f.c(AbstractEditDataActivity.java:14)
	at ryey.easer.core.ui.a.f.onOptionsItemSelected(AbstractEditDataActivity.java:3)
	at ryey.easer.core.ui.data.script.EditScriptActivity.onOptionsItemSelected(EditScriptActivity.java:2)
	at android.app.Activity.onMenuItemSelected(Activity.java:3464)
	at b.j.a.k.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.o.onMenuItemSelected(AppCompatActivity.java:1)
	at b.a.d.j.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.z.a(AppCompatDelegateImpl.java:47)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:48)
	at androidx.appcompat.view.menu.p.g(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:84)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:81)
	at androidx.appcompat.widget.ActionMenuView.a(ActionMenuView.java:16)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:6306)
	at android.view.View$PerformClick.run(View.java:24957)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Extra phone info (please complete the following information):**
 - ROM: Android 8.1.0, security patch level 5.9.2019

**Comment by wmww** [comment]
I'm also hitting this on v0.7.9-beta. Happens when script is made from event or condition. My log:
```
BUILD_CONFIG: {}
APP_VERSION_CODE: 121001
USER_CRASH_DATE: 2019-11-14T09:17:47.757-08:00
ANDROID_VERSION: 8.1.0
BRAND: OnePlus
PHONE_MODEL: ONEPLUS A6003
PRODUCT: OnePlus6
STACK_TRACE: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Set.size()' on a null object reference
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:7)
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:1)
	at ryey.easer.core.a.a.a.d.a(FileDataStorageBackendHelper.java:8)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:7)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:1)
	at ryey.easer.core.a.a.a.a(AbstractDataStorage.java:10)
	at ryey.easer.core.ui.a.f.c(AbstractEditDataActivity.java:14)
	at ryey.easer.core.ui.a.f.onOptionsItemSelected(AbstractEditDataActivity.java:3)
	at ryey.easer.core.ui.data.script.EditScriptActivity.onOptionsItemSelected(EditScriptActivity.java:2)
	at android.app.Activity.onMenuItemSelected(Activity.java:3450)
	at b.j.a.k.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.o.onMenuItemSelected(AppCompatActivity.java:1)
	at b.a.d.j.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.z.a(AppCompatDelegateImpl.java:47)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:48)
	at androidx.appcompat.view.menu.p.g(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:84)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:81)
	at androidx.appcompat.widget.ActionMenuView.a(ActionMenuView.java:16)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by renyuneyun** [comment]
Right. This should be a problem already known and fixed in v0.7.9-beta**2** (in commit f4055bcf ).

As v0.7.9-beta2 is already in the repo, could you please have a test?

**Comment by wmww** [comment]
Fix works for me

**Comment by sphh** [comment]
Looks like the fix works. Thanks @renyuneyun!
