### ISSUE TITLE
TCP Trip Event → System.err: android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by stuart12** [renyuneyun/Easer#292]
**Describe the bug**
I have a TCP Trip Event which seems to be crashing Easer 0.7.9. I have configured the event to send the text "fred" to 192.168.0.8 but do not check the reply. Easer then starts crashing and restarting in a loop. I do not have time to stop Easer before it crashes again. I can only get control of Easer again by switching my phone into airplane mode.

**To Reproduce**
Remove and reinstall Easer 0.7.9. Create a TCP Trip Event that depends on the condition that the WiFi is on. Use "adb logcat" to watch the exceptions pass by.
```
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: │ Thread: main
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: │ w.d  (EventLotus.java:1)
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: │    e.a  (TcpTripSlot.java:3)
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: │ sending TCP packet
11-23 14:59:44.389 16314 16314 V PRETTY_LOGGER: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
11-23 14:59:44.390 16314 16314 W System.err: android.os.NetworkOnMainThreadException
11-23 14:59:44.390 16314 16314 W System.err: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
11-23 14:59:44.390 16314 16314 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
11-23 14:59:44.390 16314 16314 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
11-23 14:59:44.390 16314 16314 W System.err: 	at java.net.InetAddress.getByName(InetAddress.java:1108)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:4)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.w.d(EventLotus.java:1)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.x.b(Lotus.java:2)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.EHService$c.d(EHService.java:3)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.EHService.c(EHService.java:16)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.EHService.b(EHService.java:17)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.x.a(Lotus.java:20)
11-23 14:59:44.390 16314 16314 W System.err: 	at ryey.easer.core.x.a(Lotus.java:10)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.x.a(Lotus.java:8)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.r.b(ConditionLotus.java:3)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.d.a(Unknown Source:4)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.o.b(AsyncHelper.java:1)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.b.call(Unknown Source:4)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.p.a(AsyncHelper.java:5)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.o.a(AsyncHelper.java:6)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.r.d(ConditionLotus.java:1)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.x.b(Lotus.java:2)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService$c.d(EHService.java:3)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService.c(EHService.java:16)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService.c(EHService.java:10)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService.c(EHService.java:1)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService$a.a(EHService.java:1)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.h.call(Unknown Source:2)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.p.a(AsyncHelper.java:5)
11-23 14:59:44.391 16314 16314 W System.err: 	at ryey.easer.core.EHService$a.onServiceConnected(EHService.java:4)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.os.Looper.loop(Looper.java:193)
11-23 14:59:44.391 16314 16314 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-23 14:59:44.391 16314 16314 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-23 14:59:44.391 16314 16314 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-23 14:59:44.391 16314 16314 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Expected behavior**
Easer should not crash.

**Error log:**
```
BUILD_CONFIG: {}
APP_VERSION_CODE: 121
USER_CRASH_DATE: 2019-11-23T15:08:45.671+01:00
ANDROID_VERSION: 9
BRAND: HONOR
PHONE_MODEL: KIW-L21
PRODUCT: lineage_kiwi
STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://144243690 flg=0x10 (has extras) } in ryey.easer.core.x$a@6e0bedb
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	at java.net.InetAddress.getByName(InetAddress.java:1108)
	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:4)
	at ryey.easer.core.w.d(EventLotus.java:1)
	at ryey.easer.core.x.b(Lotus.java:2)
	at ryey.easer.core.EHService$c.d(EHService.java:3)
	at ryey.easer.core.EHService.c(EHService.java:16)
	at ryey.easer.core.EHService.b(EHService.java:17)
	at ryey.easer.core.x.a(Lotus.java:20)
	at ryey.easer.core.x.a(Lotus.java:10)
	at ryey.easer.core.x$a.onReceive(Lotus.java:3)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	at java.net.InetAddress.getByName(InetAddress.java:1108)
	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:4)
	at ryey.easer.core.w.d(EventLotus.java:1)
	at ryey.easer.core.x.b(Lotus.java:2)
	at ryey.easer.core.EHService$c.d(EHService.java:3)
	at ryey.easer.core.EHService.c(EHService.java:16)
	at ryey.easer.core.EHService.b(EHService.java:17)
	at ryey.easer.core.x.a(Lotus.java:20)
	at ryey.easer.core.x.a(Lotus.java:10)
	at ryey.easer.core.x$a.onReceive(Lotus.java:3)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
BUILD_CONFIG: {}
APP_VERSION_CODE: 121
USER_CRASH_DATE: 2019-11-23T15:10:45.898+01:00
ANDROID_VERSION: 9
BRAND: HONOR
PHONE_MODEL: KIW-L21
PRODUCT: lineage_kiwi
STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://124273151 flg=0x10 (has extras) } in ryey.easer.core.x$a@5b9fbcc
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:389)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at java.net.Socket.connect(Socket.java:570)
	at java.net.Socket.<init>(Socket.java:450)
	at java.net.Socket.<init>(Socket.java:250)
	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:5)
	at ryey.easer.core.w.d(EventLotus.java:1)
	at ryey.easer.core.x.b(Lotus.java:2)
	at ryey.easer.core.EHService$c.d(EHService.java:3)
	at ryey.easer.core.EHService.c(EHService.java:16)
	at ryey.easer.core.EHService.b(EHService.java:17)
	at ryey.easer.core.x.a(Lotus.java:20)
	at ryey.easer.core.x.a(Lotus.java:10)
	at ryey.easer.core.x$a.onReceive(Lotus.java:3)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:389)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at java.net.Socket.connect(Socket.java:570)
	at java.net.Socket.<init>(Socket.java:450)
	at java.net.Socket.<init>(Socket.java:250)
	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:5)
	at ryey.easer.core.w.d(EventLotus.java:1)
	at ryey.easer.core.x.b(Lotus.java:2)
	at ryey.easer.core.EHService$c.d(EHService.java:3)
	at ryey.easer.core.EHService.c(EHService.java:16)
	at ryey.easer.core.EHService.b(EHService.java:17)
	at ryey.easer.core.x.a(Lotus.java:20)
	at ryey.easer.core.x.a(Lotus.java:10)
	at ryey.easer.core.x$a.onReceive(Lotus.java:3)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
**Extra phone info:**
 - ROM: LineageOS 16.0-20191114-NIGHTLY-kiwi
 - Device Name: KIW-L21 (Huawei Honor 5X)

**Extra logs (optional):**
```
1574518170786,2019.11.23 15:09:30.786,ASSERT,PRETTY_LOGGER,======Easer started======
1574518170815,2019.11.23 15:09:30.815,DEBUG,PRETTY_LOGGER,queryPlugin size 0
1574518176039,2019.11.23 15:09:36.039,ASSERT,PRETTY_LOGGER,======Easer started======
1574518177468,2019.11.23 15:09:37.468,ASSERT,PRETTY_LOGGER,======Easer started======
1574518177763,2019.11.23 15:09:37.763,INFO,PRETTY_LOGGER,NotificationEventListenerService onCreate()
1574518177865,2019.11.23 15:09:37.865,VERBOSE,PRETTY_LOGGER,[EHService] onCreate()
1574518178344,2019.11.23 15:09:38.344,INFO,PRETTY_LOGGER,[EHService] created
1574518178444,2019.11.23 15:09:38.444,INFO,PRETTY_LOGGER,InterruptionFilterSwitcherService onCreate()
1574518178690,2019.11.23 15:09:38.690,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518178706,2019.11.23 15:09:38.706,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518178717,2019.11.23 15:09:38.717,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518178814,2019.11.23 15:09:38.814,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518178830,2019.11.23 15:09:38.830,VERBOSE,PRETTY_LOGGER,ProfileLoaderService onCreate()
1574518178838,2019.11.23 15:09:38.838,DEBUG,PRETTY_LOGGER,[RemotePluginCommunicationHelper] begin()
1574518178967,2019.11.23 15:09:38.967,DEBUG,PRETTY_LOGGER,SSID: , BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, Supplicant state: COMPLETED, RSSI: -52, Link speed: 72Mbps, Frequency: 2422MHz, Net ID: 42, Metered hint: false, score: 60
1574518178974,2019.11.23 15:09:38.974,VERBOSE,PRETTY_LOGGER,[EHService]  onServiceConnected: ComponentInfo{ryey.easer/ryey.easer.core.ConditionHolderService}
1574518178979,2019.11.23 15:09:38.979,VERBOSE,PRETTY_LOGGER,[EHService:mSetTriggers] setting triggers
1574518179086,2019.11.23 15:09:39.086,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518179107,2019.11.23 15:09:39.107,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518179134,2019.11.23 15:09:39.134,DEBUG,PRETTY_LOGGER,{battery=power_status}
1574518179136,2019.11.23 15:09:39.136,VERBOSE,PRETTY_LOGGER,[EHService:mSetTriggers] setting trigger for <at home>
1574518179143,2019.11.23 15:09:39.143,INFO,PRETTY_LOGGER,Lotus for <at home> satisfied
1574518179262,2019.11.23 15:09:39.262,VERBOSE,PRETTY_LOGGER,sending TCP packet
1574518179289,2019.11.23 15:09:39.289,VERBOSE,PRETTY_LOGGER,[EHService:mSetTriggers] trigger for script node <at home> is set
1574518179290,2019.11.23 15:09:39.290,DEBUG,PRETTY_LOGGER,[EHService:mSetTriggers] triggers have been set
1574518179291,2019.11.23 15:09:39.291,VERBOSE,PRETTY_LOGGER,[EHService]  onServiceConnected: ComponentInfo{ryey.easer/ryey.easer.core.ProfileLoaderService}
1574518179314,2019.11.23 15:09:39.314,INFO,PRETTY_LOGGER,Lotus for <at home> satisfied
1574518179321,2019.11.23 15:09:39.321,VERBOSE,PRETTY_LOGGER,sending TCP packet
1574518181153,2019.11.23 15:09:41.153,ASSERT,PRETTY_LOGGER,======Easer started======
1574518181458,2019.11.23 15:09:41.458,DEBUG,PRETTY_LOGGER,queryPlugin size 0
```

**Additional context**
```
kiwi:/sdcard/logger/error $ sort *  | uniq -c | sort -n
      1 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://124273151 flg=0x10 (has extras) } in ryey.easer.core.x$a@5b9fbcc
      1 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://144243690 flg=0x10 (has extras) } in ryey.easer.core.x$a@6e0bedb
      1 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://185138971 flg=0x10 (has extras) } in ryey.easer.core.x$a@a7108b8
      1 USER_CRASH_DATE: 2019-11-23T15:08:45.671+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:09:09.978+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:09:30.565+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:09:49.733+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:09:57.179+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:01.211+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:08.197+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:27.154+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:35.175+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:38.397+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:41.560+01:00
      1 USER_CRASH_DATE: 2019-11-23T15:10:45.898+01:00
      2 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
      2 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
      2 	at java.net.InetAddress.getByName(InetAddress.java:1108)
      2 	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:4)
      2 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://106081966 flg=0x10 (has extras) } in ryey.easer.core.x$a@b01944f
      2 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://216716306 flg=0x10 (has extras) } in ryey.easer.core.x$a@485f7e3
      5 STACK_TRACE: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.triggerlotus.action.SLOT_SATISFIED cat=[ryey.easer.triggerlotus.category.NOTIFY_LOTUS] dat=lotus://251029468 flg=0x10 (has extras) } in ryey.easer.core.x$a@2b770e5
     12 
     12 	... 8 more
     12 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
     12 ANDROID_VERSION: 9
     12 APP_VERSION_CODE: 121
     12 BRAND: HONOR
     12 BUILD_CONFIG: {}
     12 Caused by: android.os.NetworkOnMainThreadException
     12 PHONE_MODEL: KIW-L21
     12 PRODUCT: lineage_kiwi
     12 android.os.NetworkOnMainThreadException
     22 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
     22 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
     22 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:389)
     22 	at java.net.Socket.<init>(Socket.java:250)
     22 	at java.net.Socket.<init>(Socket.java:450)
     22 	at java.net.Socket.connect(Socket.java:570)
     22 	at java.net.Socket.connect(Socket.java:621)
     22 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
     22 	at ryey.easer.j.f.h.e.a(TcpTripSlot.java:5)
     24 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
     24 	at android.app.ActivityThread.main(ActivityThread.java:6718)
     24 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
     24 	at android.os.Handler.dispatchMessage(Handler.java:99)
     24 	at android.os.Handler.handleCallback(Handler.java:873)
     24 	at android.os.Looper.loop(Looper.java:193)
     24 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
     24 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     24 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     24 	at java.lang.reflect.Method.invoke(Native Method)
     24 	at ryey.easer.core.EHService$c.d(EHService.java:3)
     24 	at ryey.easer.core.EHService.b(EHService.java:17)
     24 	at ryey.easer.core.EHService.c(EHService.java:16)
     24 	at ryey.easer.core.w.d(EventLotus.java:1)
     24 	at ryey.easer.core.x$a.onReceive(Lotus.java:3)
     24 	at ryey.easer.core.x.a(Lotus.java:10)
     24 	at ryey.easer.core.x.a(Lotus.java:20)
     24 	at ryey.easer.core.x.b(Lotus.java:2)
```

**Comment by renyuneyun** [comment]
Thanks for reporting!
I'll have a look at this and hopefully fix it soon. (In theory there shouldn't be this problem, because I did this before already.)

**Comment by renyuneyun** [comment]
I believe this has been fixed in v0.7.9.1. Shall I close this issue?

**Comment by stuart12** [comment]
Hi, I'm sorry for the delay but I cannot test this bug.  I only use TCP Trip Event after "Wifi Connection" and now WiFi Connection is never true. When I open "Edit Condition" for "WiFi Connection" I get the message "Waiting for WiFi scan result" and a pink spinner.  The waiting never finishes. This is with Easer 0.7.9.1. I have the message "Some skills do NOT have sufficient permissions" but "WiFi Connection" and "WiFi Enabled" both have green ticks next to a grey box.

**Comment by renyuneyun** [comment]
@stuart12 Just a check: do you have "Read (Coarse) Location" permission granted for Easer?
(See also #296 )

**Comment by stuart12** [comment]
I added a long comment to #296 as I will not normally have location on. I will have to find another way to not have TCP Trip Event making outgoing connections when I'm not on my home network.  Now that I know why Easer never thought I was on my home network, I'll be able to test "TCP Trip Event".

**Comment by stuart12** [comment]
TCP Trip Event now works an Android 9 (Pie) (LineageOS 16.0) and Easer 0.7.9.1 (though I don't check the reply from the remote server).  Here's [an example](https://github.com/stuart12/stuart-system/blob/073cb85d8573d1230f86b761ab54ed926a6c0f92/home-automation/home-assistant/custom_components/tcp_listener/switch.py) of how to use the event in [Home Assistant](https://www.home-assistant.io/). Thanks!
