### ISSUE TITLE
Fails to create a script

### ISSUE THREAD

**Issue by maniackcrudelis** [renyuneyun/Easer#298]
**Describe the bug**
I already have 4 scripts, whenever I try to create a fifth one it fails. Whatever the content of this script.

**To Reproduce**
1. Add a new script
2. Save
4. An error pop (too quickly to be read) and the screen return to the scripts list.

**Expected behavior:**
The script should be saved.

**Error log:**
```
BUILD_CONFIG: {}
APP_VERSION_CODE: 121001
USER_CRASH_DATE: 2019-12-25T15:15:44.520+01:00
ANDROID_VERSION: 9
BRAND: Sony
PHONE_MODEL: I4113
PRODUCT: I4113_EEA
STACK_TRACE: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Set.size()' on a null object reference
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:7)
	at ryey.easer.core.a.a.a.a.d.d.a(ScriptSerializer.java:1)
	at ryey.easer.core.a.a.a.d.a(FileDataStorageBackendHelper.java:8)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:7)
	at ryey.easer.core.a.a.a.a.d.b.a(JsonScriptDataStorageBackend.java:1)
	at ryey.easer.core.a.a.a.a(AbstractDataStorage.java:10)
	at ryey.easer.core.ui.a.f.c(AbstractEditDataActivity.java:14)
	at ryey.easer.core.ui.a.f.onOptionsItemSelected(AbstractEditDataActivity.java:3)
	at ryey.easer.core.ui.data.script.EditScriptActivity.onOptionsItemSelected(EditScriptActivity.java:2)
	at android.app.Activity.onMenuItemSelected(Activity.java:3543)
	at b.j.a.k.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.o.onMenuItemSelected(AppCompatActivity.java:1)
	at b.a.d.j.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.z.a(AppCompatDelegateImpl.java:47)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:48)
	at androidx.appcompat.view.menu.p.g(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:84)
	at androidx.appcompat.view.menu.l.a(MenuBuilder.java:81)
	at androidx.appcompat.widget.ActionMenuView.a(ActionMenuView.java:16)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:6612)
	at android.view.View.performClickInternal(View.java:6581)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25904)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Extra phone info (please complete the following information):**
 - ROM: [e.g. LineageOS 15.1]
Stock not even rooted! 

**Extra logs (optional):**

**Additional context**

**Comment by renyuneyun** [comment]
Is this the same problem as in #284 (in [this reply](https://github.com/renyuneyun/Easer/issues/284#issuecomment-546811183))?

So, a quick check: in which version of Easer do you encounter this bug? (And, did you create the previous 4 Scripts and the 5th Script in the same version?)

**Comment by maniackcrudelis** [comment]
I'm indeed using the same version 0.7.9-beta
From F-droid I see that I probably updated the app 2 month ago. So indeed, the previous scripts were created on a previous version.

So, should I wait for the next update to fix that bug ?

**Comment by renyuneyun** [comment]
The next version has fixed this bug. So just updating to anything after v0.7.9-beta would solve this problem ;p
