### ISSUE TITLE
"Notification received" event does not work

### ISSUE THREAD

**Issue by grmoth** [renyuneyun/Easer#389]
**Describe the bug**
"Notification received" event never triggers, whatever its parameters are.
Logcat shows an ClassCastException (see below)

**To Reproduce**
1. Define a "Notification received", associated with a specific app or not.
2. Trigger a corresponding notification.

**Expected behavior**
"Notification received" event is supposed to trigger.

**Error log:**
Extract from logcat :
```
D PRETTY_LOGGER: ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
D PRETTY_LOGGER: │ Thread: main 
D PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄ 
D PRETTY_LOGGER: │ NotificationEventListenerService.onNotificationPosted  (NotificationEventListenerService.java:3) 
D PRETTY_LOGGER: │    NotificationEventListenerService.g  (NotificationEventListenerService.java:1) 
D PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄ 
D PRETTY_LOGGER: │ app: <com.spotify.music> <com.spotify.music> 
D PRETTY_LOGGER: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
W Bundle  : Key android.title expected String but value was a android.text.SpannableString.  The default value <null> was returned.
W Bundle  : Attempt to cast generated internal exception: 
W Bundle  : java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String 
W Bundle  :   at android.os.BaseBundle.getString(BaseBundle.java:1199) 
W Bundle  :   at ryey.easer.skills.event.notification.NotificationEventListenerService.g(NotificationEventListenerService.java:4) 
W Bundle  :   at ryey.easer.skills.event.notification.NotificationEventListenerService.onNotificationPosted(NotificationEventListenerService.java:3) 
W Bundle  :   at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:374) 
W Bundle  :   at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2142) 
W Bundle  :   at android.os.Handler.dispatchMessage(Handler.java:106) 
W Bundle  :   at android.os.Looper.loop(Looper.java:223) 
W Bundle  :   at android.app.ActivityThread.main(ActivityThread.java:7664) 
W Bundle  :   at java.lang.reflect.Method.invoke(Native Method) 
W Bundle  :   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
W Bundle  :   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
W Bundle  : Key android.text expected String but value was a android.text.SpannableString.  The default value <null> was returned. 
W Bundle  : Attempt to cast generated internal exception: 
W Bundle  : java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String 
W Bundle  :   at android.os.BaseBundle.getString(BaseBundle.java:1199) 
W Bundle  :   at ryey.easer.skills.event.notification.NotificationEventListenerService.g(NotificationEventListenerService.java:5) 
W Bundle  :   at ryey.easer.skills.event.notification.NotificationEventListenerService.onNotificationPosted(NotificationEventListenerService.java:3) 
W Bundle  :   at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:374) 
W Bundle  :   at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2142) 
W Bundle  :   at android.os.Handler.dispatchMessage(Handler.java:106) 
W Bundle  :   at android.os.Looper.loop(Looper.java:223) 
W Bundle  :   at android.app.ActivityThread.main(ActivityThread.java:7664) 
W Bundle  :   at java.lang.reflect.Method.invoke(Native Method) 
W Bundle  :   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
W Bundle  :   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Extra phone info:**
 - ROM: CalyxOS 2.8.0 (Android 11)

**Comment by renyuneyun** [comment]
I think this can be closed as #390 is merged.
A new issue can be opened if anything new happens.
