### ISSUE TITLE
start_activity not work

### ISSUE THREAD

**Issue by y2361547758** [renyuneyun/Easer#441]
**Describe the bug**
Easer 0.8.3-beta2 

**To Reproduce**
1. set up any start_activity Profile
2. Hold and click "Trigger this Profile"
3. nothing happen

**Error log:**
I've enabled the "external logging" setting, but nothing logged, maybe some ramdon MIUI ACL refused.

**Extra phone info (please complete the following information):**
 - ROM: MIUI 13 (V13.0.5.1.45.DEV/ Android12)

**Additional context**
logcat:
```log
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Thread: main
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ProfileLoaderService.access$000  (ProfileLoaderService.java:59)
│    ProfileLoaderService.handleActionLoadProfile  (ProfileLoaderService.java:129)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ Loading profile <test> by <null>
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1090)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1066)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)
	at ryey.easer.skills.operation.intent.operations.ActivityLoader._load(ActivityLoader.java:19)
	at ryey.easer.skills.operation.intent.operations.ActivityLoader._load(ActivityLoader.java:10)
	at ryey.easer.skills.operation.OperationLoader.load(OperationLoader.java:43)
	at ryey.easer.core.SkillHelper$OperationHelper.triggerOperation(SkillHelper.java:84)
	at ryey.easer.core.ProfileLoaderService.handleActionLoadProfile(ProfileLoaderService.java:160)
	at ryey.easer.core.ProfileLoaderService.access$000(ProfileLoaderService.java:59)
	at ryey.easer.core.ProfileLoaderService$PLSBinder.triggerProfile(ProfileLoaderService.java:112)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobs.lambda$doAfterSatisfied$0(AsyncHelper.java:147)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobs.$r8$lambda$_4UneuhBMHEpUrnkShlUcLk-IKA(Unknown Source:0)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobs$$ExternalSyntheticLambda0.call(Unknown Source:4)
	at ryey.easer.core.AsyncHelper$DelayedWhenSatisfied.doAfter(AsyncHelper.java:92)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobs.doAfterSatisfied(AsyncHelper.java:145)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobs.triggerProfile(AsyncHelper.java:157)
	at ryey.easer.core.AsyncHelper$DelayedLoadProfileJobsWrapper.triggerProfile(AsyncHelper.java:210)
	at ryey.easer.core.ui.data.profile.ProfileListFragment.onContextItemSelected(ProfileListFragment.java:95)
	at androidx.fragment.app.Fragment.performContextItemSelected(Fragment.java:3133)
	at androidx.fragment.app.FragmentManager.dispatchContextItemSelected(FragmentManager.java:3240)
	at androidx.fragment.app.Fragment.performContextItemSelected(Fragment.java:3136)
	at androidx.fragment.app.FragmentManager.dispatchContextItemSelected(FragmentManager.java:3240)
	at androidx.fragment.app.Fragment.performContextItemSelected(Fragment.java:3136)
	at androidx.fragment.app.FragmentManager.dispatchContextItemSelected(FragmentManager.java:3240)
	at androidx.fragment.app.FragmentController.dispatchContextItemSelected(FragmentController.java:429)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at com.android.internal.policy.PhoneWindow$PhoneWindowMenuCallback.onMenuItemSelected(PhoneWindow.java:3790)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1221)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3214)
	at android.widget.AbsListView$3.run(AbsListView.java:4228)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by y2361547758** [comment]
seems if I want to start another app with start_activity, I need one more param `flag` with type int or array of int, maybe write in hex string
